[colors.primary]
background = "#222433"
foreground = "#d8dbe8"

[colors.cursor]
text = "CellForeground"
cursor = "#d8dbe8"

[colors.selection]
text = "CellForeground"
background = "#3b3e57"

[colors.normal]
black = "#595a5e"
red = "#f2a2a2"
green = "#b8ffbe"
yellow = "#fffeb8"
blue = "#b8c3ff"
magenta = "#f0b8ff"
cyan = "#b8f3ff"
white = "#bdbfc7"

[colors.bright]
black = "#595a5e"
red = "#f2a2a2"
green = "#b8ffbe"
yellow = "#fffeb8"
blue = "#b8c3ff"
magenta = "#f0b8ff"
cyan = "#b8f3ff"
white = "#bdbfc7"
