[colors.primary]
background = "#222534"
foreground = "#d8dbe8"

[colors.cursor]
text = "CellForeground"
cursor = "#d8dbe8"

[colors.selection]
text = "CellForeground"
background = "#353d63"

[colors.normal]
black = "#a5abca"
red = "#fea3a3"
green = "#b2fea3"
yellow = "#fee8a3"
blue = "#a3b2fe"
magenta = "#d8a3fe"
cyan = "#a3fef7"
white = "#d8dbe8"

[colors.bright]
black = "#a5abca"
red = "#fea3a3"
green = "#b2fea3"
yellow = "#fee8a3"
blue = "#a3b2fe"
magenta = "#d8a3fe"
cyan = "#a3fef7"
white = "#d8dbe8"
