[colors.primary]
background = "#0f111a"
foreground = "#dbdff0"

[colors.cursor]
text = "#0f111a"
cursor = "#dbdff0"

[colors.vi_mode_cursor]
text = "#0f111a"
cursor = "#dbdff0"

[colors.selection]
text = "#dbdff0"
background = "#31385d"

[colors.search.matches]
foreground = "#0f111a"
background = "#e9cf6b"

[colors.search.focused_match]
foreground = "#0f111a"
background = "#20bc88"

[colors.footer_bar]
foreground = "#dbdff0"
background = "#171926"

[colors.hints.start]
foreground = "#0f111a"
background = "#e9cf6b"

[colors.hints.end]
foreground = "#dbdff0"
background = "#394060"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.normal]
black = "#171926"
red = "#ef6b73"
green = "#20bc88"
yellow = "#e9cf6b"
blue = "#6f97ff"
magenta = "#bb8cff"
cyan = "#57c7d4"
white = "#dbdff0"

[colors.bright]
black = "#394060"
red = "#ff8790"
green = "#42d8a5"
yellow = "#f6e289"
blue = "#94b2ff"
magenta = "#d2aaff"
cyan = "#7ddceb"
white = "#ffffff"

[colors.dim]
black = "#0f111a"
red = "#c75a62"
green = "#1b9b71"
yellow = "#bca854"
blue = "#5879cc"
magenta = "#9570c9"
cyan = "#449da8"
white = "#8b91aa"
